---
# Implement your Pre Workload deployment tasks here

- name: usercount debug
  debug:
    msg: "Debugging num_users {{ num_users }}"

- name: create usernames
  set_fact:
    users: "{{ users | default([]) + ['user'+item | string] }}"
  loop: "{{ range(1,((num_users | int) + 1)) | list }}"

- name: Get API server URL
  k8s_facts:
    api_version: config.openshift.io/v1
    kind: Infrastructure
    name: cluster
  register: r_api_url

- name: Get Web Console route
  k8s_facts:
    api_version: route.openshift.io/v1
    kind: Route
    namespace: openshift-console
    name: console
  register: r_console_route

- name: extract DNSRecord
  k8s_info:
    kind: DNSRecord
  register: route_subdomain_r

- name: set the dnsName 
  set_fact:
    dnsName: "{{ route_subdomain_r.resources[0].spec.dnsName | trim }}"

- name: set route_subdomain 
  set_fact:
    route_subdomain: "{{ dnsName[2:-1] }}"

- name: set the master
  set_fact:
    master_url: "{{ r_api_url.resources[0].status.apiServerURL }}"

- name: set the console
  set_fact:
    console_url: "https://{{ r_console_route.resources[0].spec.host }}"

- name: debug values
  debug:
    msg:
    - "master URL: {{ master_url }}"
    - "console URL: {{ console_url }}"
    - "dnsName: {{ dnsName }}"
    - "route subdomain: {{ route_subdomain }}"
    - "ocp_username: {{ ocp_username }}"

# Leave this as the last task in the playbook.
- name: pre_workload tasks complete
  debug:
    msg: "Pre-Workload tasks completed successfully."
  when: not silent|bool
